export const ROUTES = {
	AUTH: '/auth',
	WORKFLOW: '/workflow',
	HOME: '/',
	PROFILE: '/profile',
	ADOPTION: {
		index: '/adoption',
		getAdoptablePetPath: (id: string) => `/adoption/${id}`,
	},
	BOARDING: '/boarding',
	BREEDING: { index: '/breeding', match: '/breeding/match' },
	GROOMING: '/grooming',
	SOCIAL_NETWORK: {
		index: '/social-network',
		myChats: '/social-network/my-chats',
		singleChat: '/social-network/chat/:id',
		getSingleChat: (id: string) => `/social-network/chat/${id}`,
	},
	VET_CARE: {
		index: '/vet-care',
		doctors: '/vet-care/doctors',
		bot: '/vet-care/vetica/:id',
		getBotPath: (id: string) => `/vet-care/vetica/${id}`,
		getDoctorPath: (id: string) => `/vet-care/doctors/${id}`,
	},
	TRANSPORT: '/transport',
	PERSONNEL_TRANSPORTER: '/',
	PERSONNEL_BOARDER: '/',
	PERSONNEL_GROOMER: '/',
	ADMIN: '/',
	STORE: {
		store: '/store',
		cart: '/store/cart',
		wishlist: '/store/wishlist',
		myOrders: '/store/my-orders',
		getProductPath: (id: string) => `/store/product/${id}`,
	},
	SUBSCRIPTION: '/subscription',
	ONBOARDING: '/onboarding',
	MY_PETS: {
		index: '/my-pets',
		relative: 'my-pets',
		singlePet: '/my-pets/:id',
		getMyPetPath: (id: string) => `/my-pets/${id}`,
	},
	MY_REQUESTS: '/my-requests',
	LIVE_MONITORING: {
		index: '/live/:id',
		getLive: (id: string) => `/live/${id}`,
	},
	ACTIVITY_TRACKING: {
		index: '/activity-tracking/:id',
		getActivity: (id: string) => `/activity-tracking/${id}`,
	},
};
